services:
  db:
    image: postgres:16
    container_name: discount_postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - discount

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discount_app
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    networks:
      - discount

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "/usr/local/bin/wait-for-it.sh db:5432 -- php artisan migrate"
    depends_on:
      - db
    networks:
      - discount

  nginx:
    image: nginx:alpine
    container_name: discount_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - discount

volumes:
  pgdata:

networks:
  discount:
    driver: bridge
